### ISSUE TITLE
Cannot get Workbook to Save

### ISSUE THREAD

**Issue by MSDP** [christophano/CsvHelper.Excel#1]
I get an error that it cannot find the file. If I create the file first, I get Archive Size cannot be 0, if I output data directly to a path from the ExcelSerializer, then use that file to add, it works fine but has the extra worksheet of 'Export'. 

I would like to simply populate a workbook, and save it.

See: 

    using (
                var workbook =
                    new XLWorkbook(
                        Environment.CurrentDirectory + "\\Recalls\\NCA\\OUTPUT_RECALL_" + placementId + ".xlsx",
                        XLEventTracking.Disabled))
            {
                var keepsSheet = workbook.AddWorksheet("Keeps");
                using (var csv = new CsvWriter(new ExcelSerializer(keepsSheet)))
                {
                    csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                    csv.WriteRecords(keeps);
                }
                var othersSheet = workbook.AddWorksheet("Others");
                using (var csv = new CsvWriter(new ExcelSerializer(othersSheet)))
                {
                    csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                    csv.WriteRecords(other);
                    //writer.WriteRecords(fellas);
                }
                var returnsSheet = workbook.AddWorksheet("Returns");
                using (var csv = new CsvWriter(new ExcelSerializer(returnsSheet)))
                {
                    csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                    csv.WriteRecords(returns);
                }
                workbook.Save();
            }

**Comment by MSDP** [comment]
I was finally able to do a "hacky" method to write the book.


    using (var csv = new CsvWriter(new ExcelSerializer(
                        Environment.CurrentDirectory + "\\Recalls\\NCA\\OUTPUT_RECALL_" + placementId + ".xlsx")))
            {
                csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                csv.WriteRecords(keeps);
            }

            using (
                var workbook =
                    new XLWorkbook(
                        Environment.CurrentDirectory + "\\Recalls\\NCA\\OUTPUT_RECALL_" + placementId + ".xlsx",
                        XLEventTracking.Disabled))
            {
                workbook.Worksheet("Export").Name = "Keeps";
                var othersSheet = workbook.AddWorksheet("Others");
                using (var csv = new CsvWriter(new ExcelSerializer(othersSheet)))
                {
                    csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                    csv.WriteRecords(other);
                }
                var returnsSheet = workbook.AddWorksheet("Returns");
                using (var csv = new CsvWriter(new ExcelSerializer(returnsSheet)))
                {
                    csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                    csv.WriteRecords(returns);
                }
                workbook.Save();
            }

**Comment by christophano** [comment]
"Archive size cannot be 0" happens if you create an empty file (as in, 0KB) with the xlsx extension. A proper empty xlsx file isn't truly empty, there are xml definitions, styles sheets etc.

The problem you're experiencing with the first example is that you're passing the filename into the constructor, so ClosedXml expects this to be an *existing* file.
What you need to do in this situation is to create a workbook using the empty constructor (I'd recomend passing in `XLEventTracking.Disabled` for performance reasons, though) and then use the `SaveAs` command on the workbook when you're ready.

I realise you've gone down this wrong track due to the poor examples in the read me, so I'll update them now.

**Comment by christophano** [comment]
Read me now updated with correct examples.

Happy you're found the extension useful. The important and powerful stuff is in the CsvHelper and ClosedXml extensions, my part is merely an adapter to bring them together.
