### ISSUE TITLE
Strongly Named Assembly

### ISSUE THREAD

**Issue by mdjaniga** [christophano/CsvHelper.Excel#11]
Hey first off great library.

I am having issues using it in strongly named applications.  In short, I'm attempting to sign the application myself which is resulting in really upsetting Visual Studio.  

Is it possible to strongly name the assembly?

Thanks,

Matt

**Comment by christophano** [comment]
Hi Matt,
introducing strongly named versions is something of a headache, as it's another project (albeit with linked source code files) to maintain. I may consider doing it at a future date, but for the time being the best way around this is for you to build and sign the assemblies yourself.

Chris

**Comment by mdjaniga** [comment]
Thanks for the reply and yep I agree, strongly named versions are a headache :)  Understood, I'll build and sign.

Thanks,  Matt
