### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by youngcm2** [christophano/CsvHelper.Excel#17]

**Comment by youngcm2** [comment]
I forked it, updated and published.

https://github.com/youngcm2/CsvHelper.Excel

**Comment by christophano** [comment]
The project isn't under active development, and I don't use it myself anymore.
CsvHelper changed massively in v3, so this project would require a complete rewrite - and even then I'm not sure it's possible, due to the structure of CsvHelper.
I'm happy for you to take it over, if you wish.

**Comment by youngcm2** [comment]
I am currently testing out my fork in a project.

**Comment by HenrikBagger** [comment]
@youngcm2 can you open the Issues tab in your fork? :)
