### ISSUE TITLE
CSV Class Maps

### ISSUE THREAD

**Issue by MSDP** [christophano/CsvHelper.Excel#2]
As seen below, when registering a Class Map, the Headers are not corrected in the Excel Sheet as they normally are in the CSV. They come out only as the Property Names, not the Name set in the Map. 

                var returnsSheet = workbook.AddWorksheet("Returns");
                using (var csv = new CsvWriter(new ExcelSerializer(returnsSheet)))
                {
                    csv.Configuration.RegisterClassMap<NCAKeepRecallMap>();
                    csv.WriteRecords(returns);
                }

**Comment by christophano** [comment]
Could you post an example of the class you're writing to excel and the class map for me?

**Comment by MSDP** [comment]
public class NCAKeepRecall
      {
        public string ClientId { get; set; }
        public string AcctId { get; set; }
        public string OrigAcctNum { get; set; }
        public string DebtorName { get; set; }
        public string Status { get; set; }
        public string Keeper { get; set; }
    }

    public sealed class NCAKeepRecallMap : CsvClassMap<NCAKeepRecall>
    {
        private NCAKeepRecallMap()
        {
            Map(m => m.ClientId).Name("ClientID");
            Map(m => m.AcctId).Name("AcctID");
            Map(m => m.OrigAcctNum).Name("OrigAcctNum");
            Map(m => m.DebtorName).Name("DebtorName");
            Map(m => m.Status).Name("Status");
            Map(m => m.Keeper).Name("Are You Keeping This Y/N");
        }
    }

**Comment by christophano** [comment]
I'm very confused by this issue, as the header values are determined by the CsvHelper library. The Excel Serialiser just handles serialising the values to excel.

I've ran a test using the classes you've provided, but I've found the headers are the correct values for both Csv exports and Excel exports.

```csharp
var records = new List<NCAKeepRecall>
{
    new NCAKeepRecall
    {
        AcctId = "AcctId",
        ClientId = "ClientId",
        DebtorName = "DebtorName",
        Keeper = "Keeper",
        OrigAcctNum = "OrigAcctNum",
        Status = "Status"
    }
};
using (var writer = new CsvWriter(new StreamWriter("results.csv")))
{
    writer.Configuration.RegisterClassMap<NCAKeepRecallMap>();
    writer.WriteRecords(records);
}
using (var writer = new CsvWriter(new ExcelSerializer("results.xlsx")))
{
    writer.Configuration.RegisterClassMap<NCAKeepRecallMap>();
    writer.WriteRecords(records);
}
```
