### ISSUE TITLE
Add support for starting row in ExcelParser

### ISSUE THREAD

**Issue by bgehrlei** [christophano/CsvHelper.Excel#4]
Often times I find myself receiving an auto-generated file which starts on another row other than the first.

**Comment by christophano** [comment]
Yes, I'll consider this one. Another idea is to allow you to pass a specific `Range` to the `Parser`/`Serialiser`.

**Comment by christophano** [comment]
@bgehrlei The most recent release allows you to pass in a range object itself or to specify the row and column offset.
