### ISSUE TITLE
CsvHelper.Excel adds double quotes around my string

### ISSUE THREAD

**Issue by gabygit** [christophano/CsvHelper.Excel#6]
How can I avoid CsvHelper.Excel to write "" around my string? 
```
using System.Collections.Generic;
using CsvHelper;
using CsvHelper.Excel;
using System.IO;
using ClosedXML.Excel;

namespace ConsoleApplication2
{
    public partial class Program
    {
        static void Main(string[] args)
        {
            IDictionary<string, string> map = new Dictionary<string, string>();
            map.Add("1","Museums, art galleries, and botanical and zoological gardens");
            map.Add("2", "example");
            map.Add("3", "example example");
            map.Add("4", "example, example");
            map.Add("5", "example escape \",\" example escape");
            // Write the list into a xls file then save this file
            using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                using (var writer = new CsvWriter(new ExcelSerializer(workbook)))
                {
                    writer.WriteRecords(map);
                }
                workbook.SaveAs(@"C:\Users\gabriel\Documents\Mes notes\file.xlsx", false);
            }
        }
    }
}
```
![image](https://cloud.githubusercontent.com/assets/25452154/24297931/bbfccffc-10a4-11e7-8df6-f4f9e038b256.png)

**Comment by christophano** [comment]
Hi there,
the quote is actually added by `CsvHelper` itself - `CsvHelper.Excel` is just an additional `Parser`/`Serialiser` implementation for Excel spreadsheets.

You can stop quotes being added by setting `writer.Configuration.QuoteNoFields = true;` before calling `WriteRecords`.

It would probably be helpful if `CsvHelper.Excel` set this configuration item to `false` itself, so I'll look into doingthat shortly.

**Comment by gabygit** [comment]
Thank you!

**Comment by christophano** [comment]
@gabygit Just a heads-up; I've uploaded a new release to nuget which disables this behaviour by default.
